version: '3.7'

#
# Container names have a domain-like naming scheme to facilitate dnsmasq usage.
# By ending in .doc, which is not a valid TLD, we can easily configure dnsmasq
# to resolve these names to the docker machine. This allows the containers to
# use the same names to refer to each other as the host does when resolving the
# container names.
#

services:
  auth-svc1.doc:
    build:
      context: .
      dockerfile: containers/auth-svc/Dockerfile
    image: auth-svc:latest
    container_name: auth-svc1.doc
    environment:
      NODE_ENV: development
      DEBUG: "1"
      SVC_BASE_URI: "https://haproxy.doc"
      PORT: 3001
      PROTOCOL: "http"
      TRUST_PROXY: 'true'
      REDIS_URL: 'redis://redis.doc:6379'
      OIDC_CLIENT_ID: client_id
      OIDC_CLIENT_SECRET: client_secret
      OIDC_ISSUER_URI: "https://oidc.doc:8843"
      DEFAULT_PROTOCOL: "saml"
      # allow the self-signed certs installed on shibboleth container
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      SAML_IDP_METADATA_URL: "https://shibboleth.doc:4443/idp/shibboleth"
      SAML_NAMEID_FORMAT: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
      SAML_SP_ENTITY_ID: "urn:example:sp"
    networks:
      - authen
    ports:
      - "3001:3001"
    depends_on:
      - redis.doc
  auth-svc2.doc:
    image: auth-svc:latest
    container_name: auth-svc2.doc
    environment:
      NODE_ENV: development
      DEBUG: "1"
      SVC_BASE_URI: "https://haproxy.doc"
      PORT: 3002
      PROTOCOL: "http"
      TRUST_PROXY: 'true'
      REDIS_URL: 'redis://redis.doc:6379'
      OIDC_CLIENT_ID: client_id
      OIDC_CLIENT_SECRET: client_secret
      OIDC_ISSUER_URI: "https://oidc.doc:8843"
      DEFAULT_PROTOCOL: "saml"
      # allow the self-signed certs installed on shibboleth container
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      SAML_IDP_METADATA_URL: "https://shibboleth.doc:4443/idp/shibboleth"
      SAML_NAMEID_FORMAT: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
      SAML_SP_ENTITY_ID: "urn:example:sp"
    networks:
      - authen
    ports:
      - "3002:3002"
    depends_on:
      - auth-svc1.doc
  ldap.doc:
    build:
      context: containers/ldap
    container_name: ldap.doc
    networks:
      - authen
    ports:
      - "389:389"
      - "636:636"
  haproxy.doc:
    build:
      context: containers/haproxy
    container_name: haproxy.doc
    networks:
      - authen
    ports:
      - "443:443"
    depends_on:
      - auth-svc1.doc
      - auth-svc2.doc
  oidc.doc:
    build:
      context: containers/oidc
    container_name: oidc.doc
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:8843;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: oidc-server-mock-pwd
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      API_RESOURCES_INLINE: |
        []
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId": "408616",
            "Username": "janedoe",
            "Password": "Passw0rd!",
            "Claims": [
              { "Type": "name", "Value": "Jane Doe" },
              { "Type": "given_name", "Value": "Jane" },
              { "Type": "family_name", "Value": "Doe" },
              { "Type": "email", "Value": "janedoe@example.com" },
              { "Type": "email_verified", "Value": "true" }
            ]
          },
          {
            "SubjectId": "408727",
            "Username": "johndoe",
            "Password": "Passw0rd!",
            "Claims": [
              { "Type": "name", "Value": "John Doe" },
              { "Type": "given_name", "Value": "John" },
              { "Type": "family_name", "Value": "Doe" },
              { "Type": "email", "Value": "johndoe@example.com" },
              { "Type": "email_verified", "Value": "true" }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "ClientId": "client_id",
            "ClientSecrets": [ "client_secret" ],
            "Description": "Client for client credentials flow",
            "AllowedGrantTypes": [ "authorization_code" ],
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": [
              "https://haproxy.doc/oidc/callback",
              "https://haproxy.doc"
            ],
            "AllowedScopes": [ "openid", "profile", "email" ],
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600
          }
        ]
    networks:
      - authen
    ports:
      - "8843:8843"
  # p4d.doc is in the extension repository
  redis.doc:
    image: redis:6.0
    container_name: redis.doc
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - authen
    ports:
      - "6379:6379"
  shibboleth.doc:
    build:
      context: containers/shibboleth
    container_name: shibboleth.doc
    depends_on:
      - ldap.doc
    environment:
      JETTY_BROWSER_SSL_KEYSTORE_PASSWORD: "Passw0rd!"
      JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD: "Passw0rd!"
    networks:
      - authen
    ports:
      - "4443:4443"

networks:
  authen:
    name: auth-service
