version: '3.7'

#
# Container names have a domain-like naming scheme to facilitate dnsmasq usage.
# By ending in .doc, which is not a valid TLD, we can easily configure dnsmasq
# to resolve these names to the docker machine. This allows the containers to
# use the same names to refer to each other as the host does when resolving the
# container names.
#

services:
  auth-svc.doc:
    build:
      context: .
      dockerfile: containers/auth-svc/Dockerfile
    environment:
      NODE_ENV: development
      DEBUG: "1"
      SVC_BASE_URI: "https://auth-svc.doc:3000"
      DEFAULT_PROTOCOL: "saml"
      CA_CERT_FILE: certs/ca.crt
      # would use the metadata URL but the self-signed certs are rejected
      # SAML_IDP_METADATA_URL: "https://shibboleth.doc/idp/shibboleth"
      SAML_IDP_SSO_URL: "https://shibboleth.doc/idp/profile/SAML2/Redirect/SSO"
      SAML_IDP_SLO_URL: "https://shibboleth.doc/idp/profile/SAML2/Redirect/SLO"
      SAML_NAMEID_FORMAT: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
      SAML_SP_ISSUER: "urn:example:sp"
      SP_CERT_FILE: certs/server.crt
      SP_KEY_FILE: certs/server.key
    networks:
      - authen
    ports:
      - "3000:3000"
  ldap.doc:
    build:
      context: containers/ldap
    networks:
      - authen
    ports:
      - "389:389"
      - "636:636"
  # p4d.doc is in the extension repository
  shibboleth.doc:
    build:
      context: containers/shibboleth
    depends_on:
      - ldap.doc
      - auth-svc.doc
    environment:
      JETTY_BROWSER_SSL_KEYSTORE_PASSWORD: "Passw0rd!"
      JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD: "Passw0rd!"
    networks:
      - authen
    ports:
      - "443:4443"

networks:
  authen:
    name: auth-service
