---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-creds
  namespace: helix
type: Opaque
data:
  # N.B. These values must be base64 encoded for k8s to read them properly.
  client_id: YTA1ZGZmZGItMTFhOC00YjZjLWExZTQtNjMzZDk5OWZkMmNkCg==
  client_secret: WE56OFF+Sl8tTng1Q2d3Y0gxNkxLclZQb3Z5UW15V1V5djdpeWJSTw==
...
