---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: helix
  labels:
    app: auth-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: auth-svc
...
